### PR TITLE
Some changes of GET /api/v1/reports

### PR DESCRIPTION
**Pull request by mizzy**
I made some changes to `GET /api/v1/reports` .
1. Add `until` parameter instead of `maxId` .
2. Add `count` parameter to instruct how many reports should be returned.
3. API returns `NextStart` instead of `NextId` .

@gerryhocks How do you think ?

### CODE REVIEW

**Comment by gerryhocks** [comment]
I think the changes are good and in the right direction!

I wonder if perhaps we should also have a "since" parameter, so you can do "show me all jobs since 9am" as well as "show me all jobs until 10am".

If the user wants to see only running jobs, or only failed jobs, it might also be nice to filter on the job status too. So they user could say "show me all running jobs" or even complex queries like "show me up to 50 failed jobs since yesterday at midday until this morning at 9am".

What do you think?

**Comment by mizzy** [comment]
Exactly. I will add `since` and `status` parameters.

Thanks!

**Comment by mizzy** [comment]
@gerryhocks I've added `since` and `status` . Please check them.

**Comment by gerryhocks** [comment]
@mizzy : I've compiled the some-api-changes branch and tested the API calls.. they all appear to work correctly!

I'll work on the UI and get it to use some of these new filtering options.

**Comment by mizzy** [comment]
@gerryhocks Thanks for your checking!

> I'll work on the UI and get it to use some of these new filtering options.

Thanks. Please use this branch.

**Comment by mizzy** [comment]
@gerryhocks 
I've changed the report format in 927c590 according to your advice in #4 .
Could you check it please ?

**Comment by gerryhocks** [comment]
Everything is looking good with respect to these new changes.

I've adopted my most recent UI changes to use the new Project object and it is working how I'd hoped. 

I'll commit those changes against this branch in an hour or two.

**Comment by gerryhocks** [comment]
I've pushed my changes to this branch - these changes use the new Project element and demonstrate how we can use it to navigate around projects and build reports. 

Please let me know how if these changes are suitable.

**Comment by mizzy** [comment]
Looks great to me. Thanks a lot!

I will merge this pull request and implement /api/v1/projects with a new pull request.

**Pull request merged**
