### PR TITLE
Add /api/v1/projects endpoint

### PR DESCRIPTION
**Pull request by mizzy**
- /api/v1/projects
  - Returns all projects
- /api/v1/projects/{id}
  - Returns a project which id is {id}
- /api/v1/projects?name=walter
  - Returns projects with the name like '%walter%'

### CODE REVIEW

**Comment by mizzy** [comment]
@gerryhocks Could you check this, please ?

**Comment by gerryhocks** [comment]
This looks good - the api paths you've chosen are sensible and work as expected.

The only thing I noticed is that the JSON returned by /api/v1/projects/1 includes a CreatedAt field, whereas all other objects do not have the CreatedAt field. My personal preference would be to make all the Project elements consistent for all projects calls.

**Comment by mizzy** [comment]
> The only thing I noticed is that the JSON returned by /api/v1/projects/1 includes a CreatedAt field, whereas all other objects do not have the CreatedAt field.

I've fixed in a44eff7 . Thanks!

**Comment by gerryhocks** [comment]
I've given the new commit a whirl and it all looks the same now! :)

**Comment by mizzy** [comment]
Thanks for checking! I merge this.

**Pull request merged**
